<script setup>
import { onMounted,ref } from 'vue';import IngredientAutocomplete from '../components/IngredientAutocomplete.vue';import { usePantryStore } from '../stores/pantry'
const pantry=usePantryStore(),error=ref('');onMounted(()=>pantry.fetchAll());const label=i=>i.ingredient_name??i.ingredient?.name??i.name
async function add(name){try{error.value='';await pantry.add(name)}catch(e){error.value=e.response?.data?.message??'Could not add ingredient.'}}
async function remove(id){try{await pantry.remove(id)}catch{error.value='Could not remove ingredient.'}}
function expiry(item){if(!item.expires_at)return '';const days=Math.ceil((new Date(item.expires_at)-new Date())/86400000);return days<=0?'expired':days===1?'expires tomorrow':days<4?`expires in ${days} days`:''}
</script>
<template><main class="page pantry"><header><h1 class="display-title">Your pantry ledger</h1><p class="muted">Tell us what is on hand. We’ll do the dinner arithmetic.</p></header><section class="add-card"><label>Add an ingredient</label><IngredientAutocomplete @select="add"/><p v-if="error||pantry.error" class="error" role="alert">{{ error||pantry.error }}</p></section><p v-if="pantry.loading" class="muted">Opening the pantry…</p><section v-else-if="pantry.items.length" class="items" data-test="pantry-list"><article v-for="item in pantry.items" :key="item.id" class="jar-chip" data-test="pantry-item"><span class="jar-icon"/><span>{{ label(item) }}</span><small v-if="expiry(item)">{{ expiry(item) }}</small><button :aria-label="`Remove ${label(item)}`" data-test="remove-pantry-item" @click="remove(item.id)">×</button></article></section><section v-else class="empty"><h2>The shelves are bare</h2><p>Add your first ingredient above.</p></section></main></template>
<style scoped>header p{margin-top:var(--space-2)}.add-card{margin:var(--space-8) 0;padding:var(--space-6);background:var(--color-surface);border:1px solid var(--color-line);border-radius:var(--radius-lg)}.add-card>label{display:block;margin-bottom:var(--space-2);font-weight:600}.items{display:flex;flex-wrap:wrap;gap:var(--space-3)}.jar-chip{display:flex;align-items:center;gap:var(--space-2);padding:var(--space-2) var(--space-3);background:var(--color-herb-soft);border:1px solid #c8dbc9;border-radius:var(--radius-md);color:var(--color-herb);font-weight:600}.jar-icon{width:13px;height:18px;border-radius:3px 3px 5px 5px;background:var(--color-herb)}small{color:#9a6811;font:var(--text-xs) var(--font-mono)}.jar-chip button{border:0;background:none;color:var(--color-muted);font-size:1.3rem;cursor:pointer}.empty{text-align:center;padding:var(--space-12);border:1px dashed var(--color-line);border-radius:var(--radius-lg);color:var(--color-muted)}.empty h2{font:italic var(--text-xl) var(--font-display);color:var(--color-ink);margin:0}.error{color:var(--color-tomato)}</style>
